spring.application.name=taskflow

spring.datasource.url=jdbc:mysql://localhost:3306/taskflow
spring.datasource.username=student
spring.datasource.password=student

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000
